package inventariobite;
import static inventariobite.AccederUsuario.setAcceder;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;

public class ModificarInventario extends javax.swing.JFrame {

    
    private ArrayList<Libro> ListaLibros;
    
    public ModificarInventario() {
        initComponents();
        setLocationRelativeTo(null);
        MostrarTabla();
       
    }

    
    public void MostrarTabla(){
        try{
         
        ListaLibros = new ArrayList<Libro>();
       
        File Archivo_txt = new File("Libros.txt");
        FileReader Fr;
        BufferedReader Br;
        Libro libro, aux = new Libro(0,null,null,null,null,null);
        
            Fr = new FileReader(Archivo_txt);
            Br = new BufferedReader(Fr);
            libro = aux.obtenerLibro(Br);
            
            while(libro != null){
                ListaLibros.add(libro);
                libro = aux.obtenerLibro(Br);
            }
        Br.close();
        Fr.close();
            
        
        String Mat[][] = new String[ListaLibros.size()][6];
        Libro x;
        for(int i = 0; i < ListaLibros.size(); i++){
            x = ListaLibros.get(i);
            Mat[i][0] = Integer.toString(x.getId());
            Mat[i][1] = x.getTitulo();
            Mat[i][2] = x.getAutor();
            Mat[i][3] = x.getUbicacion();
            Mat[i][4] = x.getLector();
            Mat[i][5] = x.getTipo();
        }
        
        JTable_Libros.setModel(new javax.swing.table.DefaultTableModel(
                Mat,
            new String [] {
                "ID", "Título", "Autor", "Ubicación", "Lector", "Tipo"
            }
                
        ));
        
        
        DefaultTableCellRenderer titular = new DefaultTableCellRenderer();
        titular.setBackground(new Color(239, 198, 46));
        for (int i = 0; i < JTable_Libros.getModel().getColumnCount(); i++) {
        JTable_Libros.getColumnModel().getColumn(i).setHeaderRenderer(titular);
        }
        
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Aun no se han añadido libros");
        }
    }
        
    public void limpiarCajas(){
        
        titulo_txt.setText(null);
        autor_txt.setText(null);
        ubicacion_txt.setText(null);
        id_txt.setText(null);
        tipo_txt.setText(null);
        lector_txt.setText(null);
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegresarInicio_btn = new javax.swing.JButton();
        Regresar_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Libros = new javax.swing.JTable();
        Modificar_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        titulo_txt = new javax.swing.JTextField();
        autor_txt = new javax.swing.JTextField();
        lector_txt = new javax.swing.JTextField();
        ubicacion_txt = new javax.swing.JTextField();
        tipo_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegresarInicio_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casita1.png"))); // NOI18N
        RegresarInicio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarInicio_btnActionPerformed(evt);
            }
        });
        getContentPane().add(RegresarInicio_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 40, 30));

        Regresar_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regresar2.png"))); // NOI18N
        Regresar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 40, 30));

        JTable_Libros.setBackground(new java.awt.Color(255, 255, 204));
        JTable_Libros.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        JTable_Libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Autor", "Ubicación", "Lector", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable_Libros.getTableHeader().setReorderingAllowed(false);
        JTable_Libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_LibrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_Libros);
        if (JTable_Libros.getColumnModel().getColumnCount() > 0) {
            JTable_Libros.getColumnModel().getColumn(0).setResizable(false);
            JTable_Libros.getColumnModel().getColumn(1).setResizable(false);
            JTable_Libros.getColumnModel().getColumn(2).setResizable(false);
            JTable_Libros.getColumnModel().getColumn(3).setResizable(false);
            JTable_Libros.getColumnModel().getColumn(4).setResizable(false);
            JTable_Libros.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 700, 460));

        Modificar_btn.setBackground(new java.awt.Color(255, 204, 0));
        Modificar_btn.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Modificar_btn.setText("Guardar Cambios");
        Modificar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 290, 70));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 50, 50));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setText("Título");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("Autor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setText("Ubicación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setText("Lector");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        id_txt.setEditable(false);
        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });
        getContentPane().add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 50, 30));

        titulo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulo_txtActionPerformed(evt);
            }
        });
        getContentPane().add(titulo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 290, 30));
        getContentPane().add(autor_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 290, 30));
        getContentPane().add(lector_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 290, 30));
        getContentPane().add(ubicacion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 290, 30));
        getContentPane().add(tipo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 290, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoBiteChiquito.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo 2.3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1087, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titulo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulo_txtActionPerformed

    private void Regresar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_btnActionPerformed
        Menú abrir = new Menú();
        abrir.setVisible(true);        
        dispose(); 
    }//GEN-LAST:event_Regresar_btnActionPerformed

    private void RegresarInicio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarInicio_btnActionPerformed
        setAcceder(false);
        BibliotecaDigital abrir = new BibliotecaDigital();
        abrir.setVisible(true); 
        dispose(); 
    }//GEN-LAST:event_RegresarInicio_btnActionPerformed

    private void JTable_LibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_LibrosMouseClicked
      
       int seleccion = JTable_Libros.rowAtPoint(evt.getPoint());
       
       id_txt.setText(String.valueOf(JTable_Libros.getValueAt(seleccion, 0)));
       titulo_txt.setText(String.valueOf(JTable_Libros.getValueAt(seleccion, 1)));
       autor_txt.setText(String.valueOf(JTable_Libros.getValueAt(seleccion, 2)));
       ubicacion_txt.setText(String.valueOf(JTable_Libros.getValueAt(seleccion, 3)));
       lector_txt.setText(String.valueOf(JTable_Libros.getValueAt(seleccion, 4)));
       tipo_txt.setText(String.valueOf(JTable_Libros.getValueAt(seleccion, 5)));
        
       
      
    }//GEN-LAST:event_JTable_LibrosMouseClicked

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void Modificar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_btnActionPerformed
        try{          

        String TítuloDelLIbroAModificar = JTable_Libros.getValueAt(JTable_Libros.getSelectedRow(), 1).toString();
        
            if(!titulo_txt.getText().equals("") && !autor_txt.getText().equals("") && !ubicacion_txt.getText().equals("") && !lector_txt.getText().equals("") && !tipo_txt.getText().equals("") ){
            
            int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres modificar el libro: " + TítuloDelLIbroAModificar + " ", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(opcion == JOptionPane.YES_OPTION){
            

        String titulo = titulo_txt.getText(), 
               autor = autor_txt.getText(), 
               ubicacion = ubicacion_txt.getText(), 
               lector = lector_txt.getText(), 
               tipo = tipo_txt.getText();
        Libro libro = null;
       
                   int NúmeroDeFila = JTable_Libros.getSelectedRow();
                   libro = ListaLibros.get(NúmeroDeFila);

                   libro.setTitulo(titulo);
                   libro.setAutor(autor);
                   libro.setUbicacion(ubicacion);
                   libro.setLector(lector);
                   libro.setTipo(tipo);
        
              
        File Archivo_txt = new File("Libros.txt");
        PrintWriter Pw;
        
        
            libro = null;
            Pw = new PrintWriter(Archivo_txt, "utf-8");
            for(int i = 0; i < ListaLibros.size(); i++){
                libro = ListaLibros.get(i);
                libro.guardarLibro(Pw);
            }
            Pw.close(); 
        
            
            MostrarTabla();
            limpiarCajas();
        
        }   
        }else{
            JOptionPane.showMessageDialog(null, "Debe de llenar todos los espacios en blanco para poder modificar el Libro");
        }
  
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Verifique que haya seleccionado un libro a modificar");
        }
               
    }//GEN-LAST:event_Modificar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable_Libros;
    private javax.swing.JButton Modificar_btn;
    private javax.swing.JButton RegresarInicio_btn;
    private javax.swing.JButton Regresar_btn;
    private javax.swing.JTextField autor_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lector_txt;
    private javax.swing.JTextField tipo_txt;
    private javax.swing.JTextField titulo_txt;
    private javax.swing.JTextField ubicacion_txt;
    // End of variables declaration//GEN-END:variables
}
