package inventariobite;
import static inventariobite.AccederUsuario.setAcceder;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;

public class Agregar extends javax.swing.JFrame{
   
    private ArrayList<Libro> ListaLibros;
    
    
   
    public Agregar() {
 
        initComponents();
        setLocationRelativeTo(null);
        MostrarTabla();
   
        buttonGroup1.add(niño_boton);
        buttonGroup1.add(joven_boton);
        buttonGroup1.add(adulto_boton);
        
        buttonGroup2.add(libro_boton);
        buttonGroup2.add(revista_boton);
        buttonGroup2.add(academico_boton);
        buttonGroup2.add(otro_boton);
        otro_txt.setEditable(false);
        }
    
    public void MostrarTabla(){
        
        try{
         
        ListaLibros = new ArrayList<Libro>();
       
        File Archivo_txt = new File("Libros.txt");
        FileReader Fr;
        BufferedReader Br;
        Libro libro, aux = new Libro(0,null,null,null,null,null);
        
            Fr = new FileReader(Archivo_txt);
            Br = new BufferedReader(Fr);
            libro = aux.obtenerLibro(Br);
            
            while(libro != null){
                ListaLibros.add(libro);
                libro = aux.obtenerLibro(Br);
            }
        Br.close();
        Fr.close();
            
        
        String Mat[][] = new String[ListaLibros.size()][6];
        Libro x;
        for(int i = 0; i < ListaLibros.size(); i++){
            x = ListaLibros.get(i);
            Mat[i][0] = Integer.toString(x.getId());
            Mat[i][1] = x.getTitulo();
            Mat[i][2] = x.getAutor();
            Mat[i][3] = x.getUbicacion();
            Mat[i][4] = x.getLector();
            Mat[i][5] = x.getTipo();
        }
        
        JTable_Libros.setModel(new javax.swing.table.DefaultTableModel(
                Mat,
            new String [] {
                "ID", "Título", "Autor", "Ubicación", "Lector", "Tipo"
            }
                
        ));
        
            TableColumnModel columnModel = JTable_Libros.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(40);
            columnModel.getColumn(1).setPreferredWidth(220);
            columnModel.getColumn(2).setPreferredWidth(150);
            columnModel.getColumn(3).setPreferredWidth(95);
            columnModel.getColumn(4).setPreferredWidth(85);
            columnModel.getColumn(5).setPreferredWidth(80);
        
        
        DefaultTableCellRenderer titular = new DefaultTableCellRenderer();
        titular.setBackground(new Color(239, 198, 46));
        for (int i = 0; i < JTable_Libros.getModel().getColumnCount(); i++) {
        JTable_Libros.getColumnModel().getColumn(i).setHeaderRenderer(titular);
        JTable_Libros.setEnabled(false);
        }
        
        }catch (Exception e){
            
        }
    }
    
    
    public void guardarLibros(){
        File file = new File("Libros.txt");
        PrintWriter Pw;
        
        try{
            
            Libro libro;
            Pw = new PrintWriter(file, "utf-8");
            for(int i = 0; i < ListaLibros.size(); i++){
                libro = ListaLibros.get(i);
                libro.guardarLibro(Pw);
            }
            Pw.close(); 
        }catch (Exception e){
            
     }   
     }      
        
    
    public void limpiarCajas(){
        
        titulo_txt.setText(null);
        autor_txt.setText(null);
        ubicacion_txt.setText(null);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        otro_txt.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        titulo_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        autor_txt = new javax.swing.JTextField();
        ubicacion_txt = new javax.swing.JTextField();
        niño_boton = new javax.swing.JRadioButton();
        joven_boton = new javax.swing.JRadioButton();
        adulto_boton = new javax.swing.JRadioButton();
        libro_boton = new javax.swing.JRadioButton();
        revista_boton = new javax.swing.JRadioButton();
        academico_boton = new javax.swing.JRadioButton();
        Agregar_btn = new javax.swing.JButton();
        otro_boton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Libros = new javax.swing.JTable();
        otro_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoBiteChiquito.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regresar2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 40, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casita1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 50, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setText("Título");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 75, -1, 50));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("Autor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 40));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setText("Ubicación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 175, -1, 50));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setText("Lector");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        titulo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulo_txtActionPerformed(evt);
            }
        });
        getContentPane().add(titulo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 260, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));
        getContentPane().add(autor_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 260, 30));

        ubicacion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubicacion_txtActionPerformed(evt);
            }
        });
        getContentPane().add(ubicacion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 260, 30));

        niño_boton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        niño_boton.setText("Niño");
        getContentPane().add(niño_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        joven_boton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        joven_boton.setText("Joven");
        getContentPane().add(joven_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        adulto_boton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        adulto_boton.setText("Adulto");
        getContentPane().add(adulto_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        libro_boton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        libro_boton.setText("Libro");
        libro_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libro_botonActionPerformed(evt);
            }
        });
        getContentPane().add(libro_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        revista_boton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        revista_boton.setText("Revista");
        revista_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revista_botonActionPerformed(evt);
            }
        });
        getContentPane().add(revista_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        academico_boton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        academico_boton.setText("Académico");
        academico_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academico_botonActionPerformed(evt);
            }
        });
        getContentPane().add(academico_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        Agregar_btn.setBackground(new java.awt.Color(255, 204, 0));
        Agregar_btn.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Agregar_btn.setText("Agregar Libro");
        Agregar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 400, 50));

        otro_boton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        otro_boton.setText("Otro:");
        otro_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otro_botonActionPerformed(evt);
            }
        });
        getContentPane().add(otro_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 204));

        JTable_Libros.setBackground(new java.awt.Color(255, 255, 204));
        JTable_Libros.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        JTable_Libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Autor", "Ubicación", "Lector", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable_Libros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 520, 490));
        getContentPane().add(otro_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo 2.3.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ubicacion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacion_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacion_txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menú abrir = new Menú();
        abrir.setVisible(true);        
        dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setAcceder(false);
        BibliotecaDigital abrir = new BibliotecaDigital();
        abrir.setVisible(true);        
        dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Agregar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_btnActionPerformed
        
        try{

        File Archivo_txt = new File("Libros.txt");
        if(!Archivo_txt.exists()){
                Archivo_txt.createNewFile();
        }
        
        int id = 0;    
        try{
        id = Integer.parseInt(JTable_Libros.getModel().getValueAt(JTable_Libros.getRowCount()-1, 0).toString()) + 1;
        }catch(Exception e){
            id = 1;
        }
        
        String titulo = titulo_txt.getText();
        String autor = autor_txt.getText();
        String ubicacion = ubicacion_txt.getText();
        
        String lector = null;
        if(niño_boton.isSelected()) {
            lector = "Niño";
        }
        if(joven_boton.isSelected()) {
            lector = "Joven";
        }    
        if(adulto_boton.isSelected()) {
            lector = "Adulto";
        }  
        String tipo = null;
        if(libro_boton.isSelected()) {
            tipo = "Libro";
        }
        if(academico_boton.isSelected()) {
            tipo = "Académico";
        }    
        if(revista_boton.isSelected()) {
            tipo = "Revista";
        }    
        if(otro_boton.isSelected()) {
            tipo = otro_txt.getText();
            
        }
 

        if(titulo != null && autor != null && ubicacion != null && lector != null && tipo != null){
            ListaLibros.add(new Libro(id,titulo,autor,ubicacion,lector,tipo));
            
        }else{
            JOptionPane.showMessageDialog(null, "Verifica que hayas llenado todos los campos");
        }
        
        
        }   catch (Exception e){
            
        }

        if(titulo_txt.getText() != null && autor_txt.getText() != null && ubicacion_txt.getText() != null && buttonGroup1.getSelection() != null && buttonGroup2.getSelection() != null){
            limpiarCajas();
            guardarLibros();
            MostrarTabla();
        
        JOptionPane.showMessageDialog(null, "Libro añadido con éxito");
        }
        
        
        
        
        
    }//GEN-LAST:event_Agregar_btnActionPerformed

    private void titulo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulo_txtActionPerformed

    private void otro_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otro_botonActionPerformed
        otro_txt.setEditable(true);
    }//GEN-LAST:event_otro_botonActionPerformed

    private void academico_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academico_botonActionPerformed
        otro_txt.setEditable(false);
        otro_txt.setText("");
    }//GEN-LAST:event_academico_botonActionPerformed

    private void revista_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revista_botonActionPerformed
        otro_txt.setEditable(false);
        otro_txt.setText("");
    }//GEN-LAST:event_revista_botonActionPerformed

    private void libro_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libro_botonActionPerformed
        otro_txt.setEditable(false);
        otro_txt.setText("");
    }//GEN-LAST:event_libro_botonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_btn;
    private javax.swing.JTable JTable_Libros;
    private javax.swing.JRadioButton academico_boton;
    private javax.swing.JRadioButton adulto_boton;
    private javax.swing.JTextField autor_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton joven_boton;
    private javax.swing.JRadioButton libro_boton;
    private javax.swing.JRadioButton niño_boton;
    private javax.swing.JRadioButton otro_boton;
    private javax.swing.JTextField otro_txt;
    private javax.swing.JRadioButton revista_boton;
    private javax.swing.JTextField titulo_txt;
    private javax.swing.JTextField ubicacion_txt;
    // End of variables declaration//GEN-END:variables
}
